services:
  flyway:
    image: redgate/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./db/flyway/sql:/flyway/sql
      - ./db/flyway/flyway.conf:/flyway/conf/flyway.config
    depends_on:
      - db
    container_name: tipsy_flyway
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 1P@ssw0rd2345
    ports:
      - 5432:5432
    container_name: tipsy_db
  www:
    build: ./www
    volumes:
      - ./www:/www
    ports:
      - 8000:8000
    depends_on:
      - db
      - flyway
    container_name: tipsy_www
