from enum import Enum


class RejectionReason(Enum):
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS'
    INVALID_CARD = 'INVALID_CARD'
    INVALID_CVV = 'INVALID_CVV'
    INVALID_EXPIRATION_DATE = 'INVALID_EXPIRATION_DATE'
    INVALID_CARD_HOLDER_NAME = 'INVALID_CARD_HOLDER_NAME'
    INVALID_ZIP_CODE = 'INVALID_ZIP_CODE'
    INVALID_AMOUNT = 'INVALID_AMOUNT'
    INVALID_CURRENCY = 'INVALID_CURRENCY'
    INVALID_COUNTRY = 'INVALID_COUNTRY'
    DISABLED_CARD = 'DISABLED_CARD'
    BLACKLISTED_CARD = 'BLACKLISTED_CARD'
    UNSUPPORTED_CARD = 'UNSUPPORTED_CARD'
    UNKNOWN = 'UNKNOWN'
